### ISSUE TITLE
Thanks for this slides share

### ISSUE THREAD

**Issue by tenghuanhe** [AhyoungRyu/slide-materials#1]
Hi, @AhyoungRyu 
Thanks for this slides share, it helps me a lot, I wonder if you can share some document of Zeppelin implementation details and internals, I have dive into the source code, however it is kind of difficult for a Zeppelin beginner.

Thanks & Best Regards

**Comment by AhyoungRyu** [comment]
Hi @tenghuanhe :)
Thanks for interesting Apache Zeppelin and welcome! 
What a shame... this repo is just for storing the slide images to use my real presentation...  :D
I just published the real ppt slides to [www.slideshare.net/AhyoungRyu1/apache-zeppelin-sprint](https://www.slideshare.net/secret/vtVjyNdf3moWSf). 
And here is Apache Zeppelin official ["How to contribute to Zeppelin"](https://zeppelin.apache.org/contribution/contributions.html) docs page. 

Hope this helps you!

**Comment by tenghuanhe** [comment]
Thanks very much :)
